---
layout: cv
title: David Palmer
---
# Isaac Newton
Professor of Statistics and Data Science

<div id="webaddress">
<a href="palmerda@byui.edu">palmerda@byui.edu</a>
| <a href="https://literate-adventure-lm1roqq.pages.github.io/">My GitHub page</a>
</div>


## Currently

BYU-Idaho Professor

### Specialized in

Statistics, Modeling, Statistics Education, Design and Analysis of Experiments, R and Python Programming


### Research interests

Regression, mixed models, data visualization


## Education

`1998-2002`
__BYU-Idaho__

`2002 - 2004`
__BYU__

- B.S. in Statistics

`2006-2008`
__University of Nebraska Lincoln__

- M.S. in Survey Research Methodology



## Awards

`2004`
President, Statistics National Honor Society *Mu Sigma Rho*, BYU

Valedictorian, *Kent Meridian High School*, Kent, WA



## Publications

<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) -->

In Progress

### Journals

`1669`
Newton Sir I, De analysi per æquationes numero terminorum infinitas. 

`1669`
Lectiones opticæ.

etc. etc. etc.

### Patents

`2012`
Infinitesimal calculus for solutions to physics problems, [SMBC](http://www.techdirt.com/articles/20121011/09312820678/if-patents-had-been-around-time-newton.shtml) patent 001


## Occupation

`1600`
__Royal Mint__, London

- Warden
- Minted coins

`1600`
__Lucasian professor of Mathematics__, Cambridge University



<!-- ### Footer

Last updated: May 2013 -->